const exps = [
    [ /@/gm, ' @ '],
    [ /(=e=;=u|`?e;ouab)/igm, '`e;ouab'],
    [ /(`?~?P=o=c|`?~?P¡)/gm, '~P[oic'],
    [ /\sP\[oic/gm, ' ~P[oic'],
    [ /(=o=c|¡)/igm, '[oic'],
    [ /I=y=c/gm, 'Iycouc'],
    [ /=c=w=r/gm, 'cwtyr'],
    [ /}`?agia/gm, ']`agia'],
    [ /(Pi`?(,|<)rictoc|P=,=c)/igm, 'Pi`,rictoc'],
    [ /penNou]/igm, 'pennou]'],
    [ /<eroubim/igm, ',eroubim'],
    [ /Ceravim/igm, 'ceravim'],
    [ /Emmanouyl/igm, 'Emmanouyl'],
    [ /penCwtyr/igm, 'pencwtyr'],
    [ /]Par;enoc/gm, '}par;enoc'],
    [ /pi`?~?Pneuma/gm, 'Pi`pneuma'],
    [ /(`(?=[A-Z])|`(?=:)|`(?=<)|`(?={)|`(?=})|`(?="))/gm, '~'],
    [/(\svnou]\s|\s`vnou]\s|\s~Vnou]\s|\sV}`\s|\sV]\s|\sv]\s)/igm, ' Vnou] '],
    [/(\s`mvnou]\s|\s`m`vnou]\s|\s`m~Vnou]\s|\s`mV}`\s|\s`mV]\s|\s`mv]\s)/igm, ' `mVnou] '],
    [ /Pen/gm, 'pen'],
    [ /\sny\s`?e/gm, ' ny`e'],
    [ /Kurie/gm, 'Kuri`e'],
    [ /\sPekiwt\s/gm, ' pekiwt '],
    [ /\s`?agiw\s`?~?pneumati\s/igm, ' Agiw `pneumati '],
    [ /\s`?~?Uiw\s/igm, ' ~Uiw '],
    [ /\sebol/igm, ' `ebol'],
    [ /=a=l/igm, 'allylouia'],
    [ /(}|]);e`?otokoc/igm, '};e`otokoc'],
    [ /(\+\s|\+)/igm, ''],
    [ /\s+/igm, ' '],
];